import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Vibe Mill app",
  description: "Generated by Vibe Mill.",
  generator: "Vibe Mill",
  other: {
    "vibemill:source": "autonomous",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <main className="flex-1">{children}</main>
        <footer className="border-t border-gray-200 bg-white">
          <div className="max-w-6xl mx-auto px-6 py-6 text-sm text-gray-500 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
            <p>
              Generated by Vibe Mill from a one-sentence prompt. This app was
              produced by an autonomous agent and is not a portfolio piece.
            </p>
            <a
              href="https://vibemill.dev"
              className="text-gray-700 hover:text-black underline underline-offset-2"
            >
              vibemill.dev
            </a>
          </div>
        </footer>
      </body>
    </html>
  );
}
