import Link from "next/link";
import type { App } from "@/lib/queries";

function deriveName(app: App): string {
  // Prefer the github repo slug (stable, generated by name_generator.py).
  // Fall back to a short id prefix.
  if (app.github_url) {
    const tail = app.github_url.split("/").filter(Boolean).pop();
    if (tail) return tail;
  }
  return app.id.slice(0, 8);
}

function formatTime(iso: string): string {
  const d = new Date(iso);
  const hh = String(d.getUTCHours()).padStart(2, "0");
  const mm = String(d.getUTCMinutes()).padStart(2, "0");
  return `${hh}:${mm} UTC`;
}

function archetypeLabel(app: App): string {
  // Show layout for trackers; tag HF Spaces apps so the rail is visible
  // at a glance. Vercel/JS apps are the default; no tag needed.
  const parts: string[] = [];
  if (app.archetype === "tracker" && app.layout_archetype) {
    parts.push("tracker", app.layout_archetype);
  } else {
    parts.push(app.archetype);
  }
  if (app.deploy_target === "hf_spaces") parts.push("hf");
  return parts.join(" · ");
}

export function AppCard({ app }: { app: App }) {
  const name = deriveName(app);
  const time = formatTime(app.created_at);
  const archetype = archetypeLabel(app);
  const screenshotUrl = app.screenshot_path ?? null;

  return (
    <Link
      href={`/apps/${app.id}`}
      className="group block border border-ink/10 dark:border-moon/10 hover:border-ink/30 dark:hover:border-moon/30 transition-colors"
    >
      <div className="aspect-[16/10] bg-paper-subtle dark:bg-night-subtle overflow-hidden">
        {screenshotUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={screenshotUrl}
            alt={`screenshot of ${name}`}
            className="w-full h-full object-cover object-top group-hover:opacity-90 transition-opacity"
            loading="lazy"
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center text-ink-faint dark:text-moon-faint font-mono text-xs">
            no screenshot
          </div>
        )}
      </div>
      <div className="p-3">
        <div className="font-serif text-base text-ink dark:text-moon truncate">{name}</div>
        <div className="font-mono text-xs text-ink-muted dark:text-moon-muted mt-1 truncate">
          {archetype} · {time}
        </div>
      </div>
    </Link>
  );
}
